cloud:
  aws:
    region: 
      static: us-east-1
      auto: false
    stack:      auto: false
    credentials:      access-key:  
      secret-key: 
    end-point:
      uri: https://sqs.us-east-1.amazonaws.com/405601531187/<your_queue>
   
     
      
server:  port: 8088
  
  
